### ISSUE TITLE
Non-R environment

### ISSUE THREAD

**Issue by stineb** [computationales/GECO_R_environment#2]
It would be great to have installation scripts also for non-R libraries we commonly use. These would include:

- installation manager (apt for Linux, Homebrew and MacPorts for Mac)
- gcc (with gfortran), on Mac: Xcode and Xcode Command Line Tools
- netcdf and netcdf-fortran
- udunits2
- geos
- gdal
- hdf5
- cmake
- R and Rstudio (before running the CES_R_environment scripts)
- tmux
- libsodium
- curl
- python (and a GECO_py_environment)
- ncview
- [cdo](https://code.mpimet.mpg.de/projects/cdo/)
- [nco](http://nco.sourceforge.net/)
- X Window System
- ...

**Comment by khufkens** [comment]
This is taken care of by the this (Linux only sorry).

https://github.com/bluegreen-labs/BGLabs_research_environment
