### ISSUE TITLE
Add libraries to CES environment

### ISSUE THREAD

**Issue by stineb** [computationales/GECO_R_environment#3]
## General
- devtools
- remotes

## For ingestr
- signal
- climate (from github, see https://github.com/bczernecki/climate)

## For rbeni
- ncmeta
- viridis
- ggthemes
- LSD
- yardstick
- scico
- vhs (from github: `remotes::install_github("cj-holmes/vhs")`)

**Comment by khufkens** [comment]
Not going to force an install of `rbeni` as the package fails badly - other CRAN packages are installed. It should be a personal choice to use it, but very bad practice to enforce it. Sticking to standard `ggplot()` code, and analysis files, is more transparent than wrapping everything in functions. If this needs to be considered the package should fulfill R package requirements / standards.
